// Anthony Vardaro 1001522383
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

struct TestCase {
    int arraySize;
    int multiplier;
    int * hashCounts;
};


int hash(char s[], int size, int m) {
    int value = s[0] * m*m*m + s[1] * m*m + s[2] * m;
    return value%size;
}

/**
 * Computers dynamic array of 3 letter strings that follow:
 * {aaa, aab, aac, ..., zzz}.
 * @return dynamic array of strings
 */
char ** computeHashStrings(int numStr) {
    char **strs = malloc(numStr * sizeof(char *));

    if (strs == NULL) return strs;

    char x, y, z;
    int i = 0;
    for (x = 'a'; x <= 'z'; x++) {
        for (y = 'a'; y <= 'z'; y++) {
            for (z = 'a'; z <= 'z'; z++) {
                char cur[4];
                cur[0] = x;
                cur[1] = y;
                cur[2] = z;
                cur[3] = '\0';

                strs[i] = (char *) malloc(4 * sizeof(char));
                if (strs[i] == NULL) break;

                strcpy(strs[i], cur);

                i++; // by the end of this function, i = 26^3 = numStr

            }
        }
    }

    return strs;
}

/**
 * Loop through each string to hash,
 * find the index in which it would be stored using hash()
 * dereference the hashCounts array at the index, and increment it.
 * @param strs dyanmic str array
 * @param numStr len of strs
 * @param cur TestCase ptr
 */
void computeBinCounts(char ** strs, int numStr, struct TestCase * cur) {
    int i;
    cur->hashCounts = (int *)malloc(cur->arraySize * sizeof(int *));
    for (i = 0; i < numStr; i++) {
        int index = hash(strs[i], cur->arraySize, cur->multiplier);

        int binCount = *(cur->hashCounts + index) + 1;
        *(cur->hashCounts + index) = binCount;

    }
}

/**
 * formats a struct TestCase into output
 * @param cur struct TestCase to print
 */
void printResults(struct TestCase * cur) {
    printf("size = %d, mult = %d: ", cur->arraySize, cur->multiplier);
    int i;
    for (i = 0; i < cur->arraySize; ++i) {
        if (i+1 == cur->arraySize)
            printf("%d\n", *(cur->hashCounts + i));
        else
            printf("%d, ", *(cur->hashCounts + i));
    }
    printf("\n");
}

/**
 * Frees memory allocated by computeHashStrings()
 *
 * @param hashStrings char ** generated by computeHashStrings()
 */
void freeHashStrings(char ** hashStrings) {
    int i;
    int n = sizeof(hashStrings)/sizeof(hashStrings[0]);
    for (i = 0; i < n; i++)
        free(hashStrings[i]);
    free(hashStrings);
}

int main() {
    int numStr = (int) pow(26, 3);
    char ** strs = computeHashStrings(numStr);
    struct TestCase testCases[4];
    testCases[0] = (struct TestCase){.arraySize = 123, .multiplier = 10};
    testCases[1] = (struct TestCase){.arraySize = 123, .multiplier = 31};
    testCases[2] = (struct TestCase){.arraySize = 124, .multiplier = 10};
    testCases[3] = (struct TestCase){.arraySize = 124, .multiplier = 31};

    int i;
    int len = sizeof(testCases) / sizeof(struct TestCase);

    // loop through each test case
    // compute number of collisions at each index for current iteration
    // print the results and free the cur.hashCounts ptr;
    for (i = 0; i < len; i++) {
        struct TestCase * cur = &testCases[i];
        computeBinCounts(strs, numStr, cur);
        printResults(cur);
        free(cur->hashCounts);
    }

    freeHashStrings(strs);

    return 0;
}